name: Test Python

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # Required to checkout repository

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Run pytest
        run: uv run pytest --verbose
